name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - '.github/**'
      - 'README.**'
  release:
  repository_dispatch:
    types: 
      - trigger-ci

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Get current ref
      id: bare_ref
      run: echo ::set-output name=REF::${GITHUB_REF##*/}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      id: buildx
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:master
          network=host
      
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
          type=ref,enable=true,priority=700,prefix=,suffix=,event=tag
          type=ref,enable=true,priority=800,prefix=pr-,suffix=,event=pr
          type=semver,priority=900,pattern={{version}},value=${{ github.event.client_payload.ref }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: VERSION=${{ steps.bare_ref.outputs.REF }}
